name: Python Code Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allows manual triggering

jobs:
  lint-and-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy isort black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./app --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 ./app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Check formatting with black
        run: |
          black --check ./app

      - name: Check imports with isort
        run: |
          isort --check-only --profile black ./app

      - name: Type check with mypy
        run: |
          mypy --ignore-missing-imports ./app

      - name: Verify application starts
        run: |
          cd app
          # Start application in background and check if it initializes correctly
          python -c "import main; app = main.app" || exit 1
      - name: Completed the lint
        run: echo "✅ All checks completed successfully."
